# Base URL
baseurl: https://rzuckerm.github.io/sample-programs-website-copy

# Theme data
theme: jekyll-theme-dinky
title: Sample Programs in Every Language
description: A Collection of Code Snippets in as Many Programming Languages as Possible
show_downloads: true

# Data
image_path: /assets/images/
title_image: sample-programs-in-every-language.jpg

# Repo metadata
repository: rzuckerm/sample-programs-website-copy

# File exclusion settings
exclude: ["CNAME", "Gemfile", "templates", "vendor/bundle"]

# Posts permalink
permalink: /:categories/:title/

# Extra plugins
plugins:
  - jekyll-feed # See https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-sitemap # See https://github.com/jekyll/jekyll-sitemap

github:
  zip_url: https://github.com/rzuckerm/sample-programs-website-copy/zipball/main
  tar_url: https://github.com/rzuckerm/sample-programs-website-copy/tarball/main
  repository_url: https://github.com/rzuckerm/sample-programs-website-copy

# Markdown settings
kramdown:
    smart_quotes: apos,apos,quot,quot
