name: Website Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  images:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Webpages
        run: python scripts/automate.py

      - name: Rewrite URLs
        run: |
          find docs/ -name '*.md' -exec sed -i 's!https://sampleprograms\.io/!https://rzuckerm.github.io/sample-programs-website-copy/!g' '{}' ';'

      - name: Generate Images
        run: |
          sources=sources/images/
          images=docs/assets/images/generated/
          logo=../icon-small.png
          for file in "$sources"*
          do
            image-titler --path "$file" --output "$images" --logo "$images$logo"
            filename=$(basename "$file")
            edit=$(cd "$images" && ls -t | head -n1)
            mv "$images$edit" "$images$filename" 
          done

      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build Webpages with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs/
          destination: docs/_site
          token: ${{ secrets.REPO_TOKEN }}

      - name: Upload Webpages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_site
          token: ${{ secrets.REPO_TOKEN }}
